<?php
/**
 * ProjectPhaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project API
 *
 * ConnectWise Project API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Project;

/**
 * ProjectPhaseTest Class Doc Comment
 *
 * @category    Class */
// * @description ProjectPhase
/**
 * @package     Spinen\ConnectWise\Clients\Project
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectPhaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProjectPhase"
     */
    public function testProjectPhase()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "board"
     */
    public function testPropertyBoard()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "opportunity"
     */
    public function testPropertyOpportunity()
    {

    }

    /**
     * Test attribute "parent_phase"
     */
    public function testPropertyParentPhase()
    {

    }

    /**
     * Test attribute "wbs_code"
     */
    public function testPropertyWbsCode()
    {

    }

    /**
     * Test attribute "bill_time"
     */
    public function testPropertyBillTime()
    {

    }

    /**
     * Test attribute "bill_expenses"
     */
    public function testPropertyBillExpenses()
    {

    }

    /**
     * Test attribute "bill_products"
     */
    public function testPropertyBillProducts()
    {

    }

    /**
     * Test attribute "mark_as_milestone_flag"
     */
    public function testPropertyMarkAsMilestoneFlag()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "deadline_date"
     */
    public function testPropertyDeadlineDate()
    {

    }

    /**
     * Test attribute "bill_separately_flag"
     */
    public function testPropertyBillSeparatelyFlag()
    {

    }

    /**
     * Test attribute "billing_method"
     */
    public function testPropertyBillingMethod()
    {

    }

    /**
     * Test attribute "scheduled_hours"
     */
    public function testPropertyScheduledHours()
    {

    }

    /**
     * Test attribute "scheduled_start"
     */
    public function testPropertyScheduledStart()
    {

    }

    /**
     * Test attribute "scheduled_end"
     */
    public function testPropertyScheduledEnd()
    {

    }

    /**
     * Test attribute "actual_hours"
     */
    public function testPropertyActualHours()
    {

    }

    /**
     * Test attribute "actual_start"
     */
    public function testPropertyActualStart()
    {

    }

    /**
     * Test attribute "actual_end"
     */
    public function testPropertyActualEnd()
    {

    }

    /**
     * Test attribute "budget_hours"
     */
    public function testPropertyBudgetHours()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "hourly_rate"
     */
    public function testPropertyHourlyRate()
    {

    }

    /**
     * Test attribute "billing_start_date"
     */
    public function testPropertyBillingStartDate()
    {

    }

    /**
     * Test attribute "bill_phase_closed_flag"
     */
    public function testPropertyBillPhaseClosedFlag()
    {

    }

    /**
     * Test attribute "bill_project_closed_flag"
     */
    public function testPropertyBillProjectClosedFlag()
    {

    }

    /**
     * Test attribute "downpayment"
     */
    public function testPropertyDownpayment()
    {

    }

    /**
     * Test attribute "po_number"
     */
    public function testPropertyPoNumber()
    {

    }

    /**
     * Test attribute "po_amount"
     */
    public function testPropertyPoAmount()
    {

    }

    /**
     * Test attribute "estimated_time_cost"
     */
    public function testPropertyEstimatedTimeCost()
    {

    }

    /**
     * Test attribute "estimated_expense_cost"
     */
    public function testPropertyEstimatedExpenseCost()
    {

    }

    /**
     * Test attribute "estimated_product_cost"
     */
    public function testPropertyEstimatedProductCost()
    {

    }

    /**
     * Test attribute "estimated_time_revenue"
     */
    public function testPropertyEstimatedTimeRevenue()
    {

    }

    /**
     * Test attribute "estimated_expense_revenue"
     */
    public function testPropertyEstimatedExpenseRevenue()
    {

    }

    /**
     * Test attribute "estimated_product_revenue"
     */
    public function testPropertyEstimatedProductRevenue()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
