<?php
/**
 * ProjectContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project API
 *
 * ConnectWise Project API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Project;

use \Spinen\ConnectWise\Clients\Project\Configuration;
use \Spinen\ConnectWise\Clients\Project\ApiClient;
use \Spinen\ConnectWise\Clients\Project\ApiException;
use \Spinen\ConnectWise\Clients\Project\ObjectSerializer;

/**
 * ProjectContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for projectProjectsIdContactsContactIdDelete
     *
     * .
     *
     */
    public function testProjectProjectsIdContactsContactIdDelete()
    {

    }

    /**
     * Test case for projectProjectsIdContactsContactIdGet
     *
     * .
     *
     */
    public function testProjectProjectsIdContactsContactIdGet()
    {

    }

    /**
     * Test case for projectProjectsIdContactsGet
     *
     * .
     *
     */
    public function testProjectProjectsIdContactsGet()
    {

    }

    /**
     * Test case for projectProjectsIdContactsPost
     *
     * .
     *
     */
    public function testProjectProjectsIdContactsPost()
    {

    }

}
