<?php
/**
 * ProjectsTeamMembersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project API
 *
 * ConnectWise Project API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Project;

use \Spinen\ConnectWise\Clients\Project\Configuration;
use \Spinen\ConnectWise\Clients\Project\ApiClient;
use \Spinen\ConnectWise\Clients\Project\ApiException;
use \Spinen\ConnectWise\Clients\Project\ObjectSerializer;

/**
 * ProjectsTeamMembersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsTeamMembersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersCountGet
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersCountGet()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersGet
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersGet()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersPost
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersPost()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersTeamMemberIdDelete
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersTeamMemberIdDelete()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersTeamMemberIdGet
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersTeamMemberIdGet()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersTeamMemberIdPatch
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersTeamMemberIdPatch()
    {

    }

    /**
     * Test case for projectProjectsIdTeamMembersTeamMemberIdPut
     *
     * .
     *
     */
    public function testProjectProjectsIdTeamMembersTeamMemberIdPut()
    {

    }

}
