<?php
/**
 * ProjectNotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Project API
 *
 * ConnectWise Project API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Project;

use \Spinen\ConnectWise\Clients\Project\Configuration;
use \Spinen\ConnectWise\Clients\Project\ApiClient;
use \Spinen\ConnectWise\Clients\Project\ApiException;
use \Spinen\ConnectWise\Clients\Project\ObjectSerializer;

/**
 * ProjectNotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Project
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectNotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for projectProjectsIdNotesCountGet
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesCountGet()
    {

    }

    /**
     * Test case for projectProjectsIdNotesGet
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesGet()
    {

    }

    /**
     * Test case for projectProjectsIdNotesNoteIdDelete
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesNoteIdDelete()
    {

    }

    /**
     * Test case for projectProjectsIdNotesNoteIdGet
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesNoteIdGet()
    {

    }

    /**
     * Test case for projectProjectsIdNotesNoteIdPatch
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesNoteIdPatch()
    {

    }

    /**
     * Test case for projectProjectsIdNotesNoteIdPut
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesNoteIdPut()
    {

    }

    /**
     * Test case for projectProjectsIdNotesPost
     *
     * .
     *
     */
    public function testProjectProjectsIdNotesPost()
    {

    }

}
